<div class="card my-4">
	<div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
		<div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
			<h6 class="text-white text-capitalize ps-3">SizesTable</h6>
		</div>
	</div>
	<div class="card-body px-0 pb-2">
		<div class="table-responsive p-0">
			<p class="text-secondary opacity-7">
				<a href="<?= $this->url('size', ['action' => 'add']) ?>">Ajouter une nouvelle taille </a>
			</p>
			<table class="table align-items-center mb-0">
				<thead>
					<tr>
						<th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">marque</th>
						<th class="text-secondary opacity-5">Action</th>
					</tr>
				</thead>
				<tbody>
					<?php
					foreach ($sizes as $size) {
					?>
						<tr>
							<td>
								<div class="d-flex px-2 py-1">

									<div class="d-flex flex-column justify-content-center">
										<h6 class="mb-0 text-sm"><?= $this->escapeHtml($size->size) ?></h6>
										<p class="text-xs text-secondary mb-0"><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="23494c4b4d6340514642574a55460e574a4e0d404c4e"> </a></p>
									</div>
								</div>
							</td>

							<td class="align-middle">
								<a href="javascript:;" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
									<a href="<?= $this->url('size', ['action' => 'edit', 'id' => $size->id]) ?>">Edit</a>
									<a href="<?= $this->url('size', ['action' => 'delete', 'id' => $size->id]) ?>">Delete</a>
								</a>
							</td>
						</tr>
					<?php
					}
					?>
				</tbody>
			</table>
		</div>
	</div>
</div>










<?php
// module/book/view/book/book/index.phtml:
/*
$title = 'Ajouter une taille';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('size', ['action' => 'add']) ?>">Ajouter une nouvelle Taille </a>
</p>

<table class="table">
    <tr>
        <th>Taille</th>
        <th>Action</th>

    </tr>
    <?php foreach ($sizes as $size) : ?>
        <tr>
            <td><?= $this->escapeHtml($size->size) ?></td>

            <td>
                <a href="<?= $this->url('size', ['action' => 'edit', 'id' => $size->id]) ?>">Edit</a>
                <a href="<?= $this->url('size', ['action' => 'delete', 'id' => $size->id]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>*/