<div class="grid-filter-wrap">
	<!--Portfolio Filter
===========================================-->
	<ul class="grid-filter" data-container="#portfolio">
		<li class="activeFilter"><a href=" #" data-filter="*">Voir tout</a></li>

		<?php
		foreach ($colors as $color) {
		?>
			<li class=""><a href="#" data-filter=".pf-color<?= $color->id; ?>"><?= $color->color; ?></a></li>

		<?php
		}
		?>
	</ul>

</div>

<!-- class AJAX -->

<!--div  class="ajax-shoes pt-5 pb-5"></!--div>

<!-end -->
<div id="portfolio" class=" portfolio row grid-container gutter-30" data-layout="fitRows">
	<?php
	foreach ($shoes as $shoe) {
		//d($shoe);
	?>
		<article class="portfolio-item col-md-4 col-sm-6 col-12 pf-color<?= $shoe->color; ?>">
			<div class="grid-inner">
				<div class="portfolio-image">
					<a href="#">
						<img src="/img/<?= $shoe->img; ?>" class="avatar avatar-sm me-3 border-radius-lg" style=" width:200 !important">
					</a>
					<div class="bg-overlay">
						<div class="bg-overlay-content dark" data-hover-animate="fadeIn">
							<a href="#" class="overlay-trigger-icon bg-light text-dark" data-hover-animate="fadeInDownSmall" data-hover-animate-out="fadeOutUpSmall" data-hover-speed="350" data-lightbox="image" title="Image"><i class="icon-line-plus"></i></a>
							<a href="#" class="overlay-trigger-icon bg-light text-dark" data-hover-animate="fadeInDownSmall" data-hover-animate-out="fadeOutUpSmall" data-hover-speed="350"><i class="icon-line-ellipsis"></i></a>
						</div>
						<div class="bg-overlay-bg dark" data-hover-animate="fadeIn"></div>
					</div>
				</div>
				<div class="portfolio-desc">
					<h3>
						<!--a href="<!?= $this->url('detail_shoes', ['action' => 'index', 'id' => $shoe->id]) ?>"><!?= $shoe->sizeType; ?></a-->

					</h3>

					<span>
						<a href=" #"> <?= $shoe->typeShoes; ?> </a>
					</span>
					<span>
						<a href=" #"><?= $shoe->shoesSize; ?></a>
					</span>

				</div>


			</div>
		</article>
	<?php
	}
	?>
</div>