
<table class="table align-items-center mb-0">
		  <thead>
			  <?php
	foreach ($admins as $accessory) {
	?>
			<tr>
			  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Image</th>
			  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Nom</th>
			  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Groupe</th>
			  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Edit</th>
			  <th class="text-secondary opacity-7"></th>
			</tr>
		  </thead>
		  <tbody>
			<tr>
			  <td>
				<div class="d-flex px-2 py-1">
				  <div>
					<img src="/img/<?= $accessory->img; ?>" class="avatar avatar-sm me-3 border-radius-lg" alt="user1">
				  </div>
				  <div class="d-flex flex-column justify-content-center">
					<h6 class="mb-0 text-sm">John Michael</h6>
					<p class="text-xs text-secondary mb-0"><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="23494c4b4d6340514642574a55460e574a4e0d404c4e">[email&#160;protected]</a></p>
				  </div>
				</div>
			  </td>
			  <td>
				<p class="text-xs font-weight-bold mb-0">Manager</p>
				<p class="text-xs text-secondary mb-0">Organization</p>
			  </td>
			  <td class="align-middle text-center text-sm">
				<span class="badge badge-sm bg-gradient-success">Online</span>
			  </td>
			  <td class="align-middle text-center">
				<span class="text-secondary text-xs font-weight-bold">23/04/18</span>
			  </td>
			  <td class="align-middle">
				<a href="javascript:;" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
				  Edit
				</a>
			  </td>
			</tr>
				</table>