<?php
$shoesSize = $form->get('shoesSize');
$shoesSize->setAttribute('class', 'form-control');
$shoesSize->setAttribute('placeholder', 'Taille');

$typeShoes = $form->get('typeShoes');
$typeShoes->setAttribute('class', 'form-control');
$typeShoes->setAttribute('placeholder', 'Shoes type');


$img = $form->get('img');
$img->setAttribute('class', 'form-control');
$img->setAttribute('placeholder', 'Image');


$brand = $form->get('brand');
$brand->setAttribute('class', 'form-control');
$brand->setAttribute('placeholder', 'Marque');



$color = $form->get('color');
$color->setAttribute('class', 'form-control');
$color->setAttribute('placeholder', 'Color');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');
$form->setAttribute('action', $this->url('shoes', ['action' => 'add']));
$form->prepare();
//d($form->getMessages());
echo $this->form()->openTag($form);
?>

<main class="main-content  mt-0">
    <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');">
        <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container my-auto">
            <div class="row">
                <div class="col-lg-4 col-md-8 col-12 mx-auto">
                    <div class="card z-index-0 fadeIn3 fadeInBottom">
                        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                            <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                                <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">Ajouter une nouvelle chaussure</h4>
                                <div class="row mt-3">
                                    <div class="col-2 text-center ms-auto">
                                        <a class="btn btn-link px-3" href="javascript:;">
                                            <i class="fa fa-facebook text-white text-lg"></i>
                                        </a>
                                    </div>
                                    <div class="col-2 text-center px-1">
                                        <a class="btn btn-link px-3" href="javascript:;">
                                            <i class="fa fa-github text-white text-lg"></i>
                                        </a>
                                    </div>
                                    <div class="col-2 text-center me-auto">
                                        <a class="btn btn-link px-3" href="javascript:;">
                                            <i class="fa fa-google text-white text-lg"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card-body">


                            <!--label-->
                            <?= $this->formLabel($shoesSize) ?>
                            <div class="input-group input-group-outline my-3">
                                <!--echo input-->
                                <?= $this->formElement($shoesSize) ?>
                                <!--afficher erreur -->
                                <?= $this->formElementErrors()->render($shoesSize, ['class' => 'help-block']) ?>

                            </div>

                            <!--label-->
                            <?= $this->formLabel($typeShoes) ?>
                            <div class="input-group input-group-outline my-3">
                                <!--echo input-->
                                <?= $this->formElement($typeShoes) ?>
                                <!--afficher erreur -->
                                <?= $this->formElementErrors()->render($typeShoes, ['class' => 'help-block']) ?>
                            </div>
                            <!--label-->
                            <?= $this->formLabel($color) ?>
                            <div class="input-group input-group-outline my-3">
                                <!--echo input-->
                                <?= $this->formElement($color) ?>
                                <!--afficher erreur -->
                                <?= $this->formElementErrors()->render($color, ['class' => 'help-block']) ?>
                            </div>



                            <!--label-->
                            <?= $this->formLabel($brand) ?>
                            <div class="input-group input-group-outline my-3">
                                <!--echo input-->
                                <?= $this->formElement($brand) ?>
                                <!--afficher erreur -->
                                <?= $this->formElementErrors()->render($brand, ['class' => 'help-block']) ?>
                            </div>
                            <!--label-->



                            <!--label-->
                            <?= $this->formLabel($img) ?>
                            <div class="input-group input-group-outline my-3">
                                <!--echo input-->
                                <?= $this->formElement($img) ?>
                                <!--afficher erreur -->
                                <?= $this->formElementErrors()->render($img, ['class' => 'help-block']) ?>
                            </div>


                            <?php
                            echo $this->formSubmit($submit);
                            echo $this->formHidden($form->get('id'));
                            echo $this->form()->closeTag();
                            ?>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<!--   Core JS Files   -->
<script src="../assets/js/core/popper.min.js"></script>
<script src="../assets/js/core/bootstrap.min.js"></script>
<script src="../assets/js/plugins/perfect-scrollbar.min.js"></script>
<script src="../assets/js/plugins/smooth-scrollbar.min.js"></script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>
<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="../assets/js/material-dashboard.min.js?v=3.0.1"></script>
</body>

</html>