<?php
$title = 'Supprimer chaussure';
$url   = $this->url('shoes', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Vous êtes sûre de vouloir supprimer

    "<?= $this->escapeHtml($shoes->typeShoes) ?>"


<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $shoes->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>

</form>