<!DOCTYPE>
<html xml:lang="fr">


<body>
  <form action="<?= $this->url('log', ["action" => "processform"]) ?>" method="post">
    <fieldset>
      <legend>Identifiez-vous!</legend>
      <?php
      // Rencontre-t-on une erreur ?
      if (!empty($errorMessage)) {
        echo '<p>', htmlspecialchars($errorMessage), '</p>';
      }
      ?>
      <p>
      <div class="form-group">
        <label for="formGroupExampleInput">Login :</label>
        <input type="text" name="login" class="form-control" id="formGroupExampleInput" placeholder="Login">
      </div>
      <div class="form-group">
        <label for="formGroupExampleInput2">Password :</label>
        <input type="password" name="password" class="form-control pl-3 rounded" id="formGroupExampleInput2" placeholder="password">
      </div>
      <div>
        <input type="submit" class="btn btn-primary" name="submit" value="Se connecter" />
      </div>
    </fieldset>
  </form>
</body>

</html>