<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">

            <div class="single-product">
                <div class="product">
                    <div class="row gutter-40">

                        <div class="col-md-5">

                            <!-- Product Single - Gallery
									============================================= -->
                            <div class="product-image">
                                <div class="fslider" data-pagi="false" data-arrows="false" data-thumbs="true">
                                    <div class="flexslider">
                                        <div class="slider-wrap" data-lightbox="gallery">
                                            <div class="slide" data-thumb="images/shop/thumbs/dress/3.jpg"> <img src="/img/<?= $accessory->img; ?>" alt="Open Imagination">
                                                <span><a href="#"><?= $accessory->name_color; ?></a></span>
                                            </div>
                                            <div class="bg-overlay-content align-items-end justify-content-between" data-hover-animate="fadeIn" data-hover-speed="400">
                                                <a href="#" class="btn btn-dark me-2"><i class="icon-shopping-basket"></i></a>
                                                <a href="include/ajax/shop-item.html" class="btn btn-dark" data-lightbox="ajax"><i class="icon-line-expand"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- Product Single - Gallery End -->
                        <div class="col-md-5 product-desc">
                            <div class="d-flex align-items-center justify-content-between">
                                <!-- Product Single - Price
								============================================= -->
                                <div class="product-price " <?= $accessory->price; ?>><?= $accessory->price; ?></div><!-- Product Single - Price End -->
                                <!-- Product Single - Rating
								============================================= -->
                                <div class="product-rating">
                                    <div class="stars">
                                        <i class="icon-star3-active"></i>
                                        <i class="icon-star3"></i>
                                        <i class="icon-star3"></i>
                                        <i class="icon-star-half-full"></i>
                                        <i class="icon-star-empty"></i>
                                    </div>
                                    <a href="#">Voir les avis.</a>
                                </div>
                                <!-- Product Single - Rating End -->

                            </div>

                            <div class="line"></div>

                            <!-- Product Single - Quantity & Cart Button
									============================================= -->
                            <form class="cart mb-0 d-flex justify-content-between align-items-center" method="post" enctype='multipart/form-data'>
                                <div class="quantity clearfix">
                                    <input type="button" value="-" class="minus">
                                    <input type="number" step="1" min="1" name="quantity" value="1" title="Qty" class="qty" />
                                    <input type="button" value="+" class="plus">
                                </div>
                                <form>
                                    <a href="<?= $this->url('panier') ?>">
                                        <button type="submit" class="add-to-cart button m-0">Ajouter au panier

                                    </a>


                                </form>
                            </form><!-- Product Single - Quantity & Cart Button End -->
                        </div>
                        <div class="col-12 mt-5">
                            <div class="tabs clearfix mb-0" id="tab-1">
                                <ul class="tab-nav clearfix">
                                    <li>
                                        <a href="#tabs-1"><i class="icon-align-justify2"></i><span class="d-none d-md-inline-block"> Description</span></a>
                                    </li>
                                </ul>
                                <p><?= $this->escapeHtml($accessory->description) ?></p>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>