<!--?php
 // Definition des constantes et variables
  define('LOGIN','toto');
  define('PASSWORD','tata');
  $_SESSION['connect']=0;
  $errorMessage = '';



  // Test de l'envoi du formulaire
 if (isset($_POST['submit']))
  {
    // Les identifiants sont transmis ?
    if(isset($_POST['login']) && isset($_POST['password'])) 
    {
      // Sont-ils les mêmes que les constantes ?
      if($_POST['login'] !== LOGIN) 
      {
        $errorMessage = 'Mauvais login !';
      }
        elseif($_POST['password'] !== PASSWORD) 
      {  
        $errorMessage = 'Mauvais password !';
      }
        else
      {
			// On enregistre le login en session
			// $_SESSION['login'] = LOGIN;
			if($_POST['login'] == LOGIN && $_POST['password'] == PASSWORD && $_SESSION['connect']= 1){
				// On ouvre la session
				session_start();
				$_SESSION['login'] = LOGIN;
				$_SESSION['password'] = PASSWORD;
				 //Change la valeur de la variable connect. C'est elle qui nous permettra de savoir s'il y a eu identification
				var_dump($_SESSION); 
				 //print_r($_SESSION) ;
				
				// On redirige vers la page admin 
			 if(isset($_SESSION['login'])){
				 	header('Location: http://amira.gsvcom.fr/admin');
			         exit();

				}
		
			}
			
      }
	

	 }else
		{
		  $errorMessage = 'Veuillez inscrire vos identifiants svp !';
		}
  }
?-->
<!DOCTYPE html">
<html  xml:lang="fr">
  <head>
    <title>Formulaire d'authentification</title>
  </head>
  <body>
    <form action="<?= $this->url('log',["action" => "processform"]) ?>" method="post">
      <fieldset>
        <legend>Identifiez-vous</legend>
        <?php
          // Rencontre-t-on une erreur ?
          if(!empty($errorMessage)) 
          {
            echo '<p>', htmlspecialchars($errorMessage) ,'</p>';
          }
        ?>
       <p>
          <label for="login">Login :</label> 
          <input type="text" name="login" id="login" value="" />
        </p>
        <p>
          <label for="password">Password :</label> 
          <input type="password" name="password" id="password" value="" /> 
          <input type="submit" name="submit" value="Se connecter" />
        </p>
      </fieldset>
    </form>
  </body>
</html>

















