<div class="content-wrap">
    <div class="container clearfix">
        <div class="row align-items-stretch gutter-20 mb-5 min-vh-60">
            <div class="col-xl-8 min-vh-50">
                <div class="fslider h-100" data-arrows="false">
                    <div class="flexslider">
                        <div class="slider-wrap">
                            <div class="slide">
                                <a href="#">

                                    <img src="/assets/images/slider/1.avif" alt="Shop Image1">

                                </a>
                            </div>
                            <div class="slide">
                                <a href="#">
                                    <img src="/assets/images/slider/1.jpg" alt="Shop Image">
                                </a>
                            </div>
                            <div class="slide flex-active-slide">
                                <a href="#">
                                    <img src="/assets/images/slider/3.avif" alt="Shop Image3">
                                </a>
                            </div>
                            <div class="slide">
                                <a href="#">
                                    <img src="/assets/images/slider/4.avif" alt="Shop Image4">
                                </a>
                            </div>

                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
    <div class="promo parallax promo-full bottommargin-lg" style="background-image: url('images/parallax/3.jpg');" data-bottom-top="background-position:0px 300px;" data-top-bottom="background-position:0px -300px;">
        <div class="container clearfix">
            <div class="row align-items-center">
                <div class="col-12 col-lg">
                    <h3><span>-30%</span> sur une selection d'articles *</h3>
                    <span>Vente disponible sur une sélection de marques de créateurs comprenant des vêtements, des chaussures, des accessoires de mode et des montres.</span>
                </div>
                <div class="col-12 col-lg-auto mt-4 mt-lg-0">
                    <a href="#" class="button button-large button-circle m-0">Je shoppe!</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row justify-content-center col-mb-50 mb-0">
            <div class="col-sm-6 col-lg-4">
                <div class="feature-box text-center media-box fbox-bg">
                    <div class="fbox-media">
                        <img src="/img/80.jpg.avif" alt="Image">
                    </div>
                    <div class="fbox-content">
                        <h3>Casual style<span class="subtitle">Nouveautés du printemps</span></h3>
                        <p><a href="#" class="btn btn-secondary">Shoppe la marque</a></p>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-lg-4">
                <div class="feature-box text-center media-box fbox-bg">
                    <div class="fbox-media">
                        <img src="/img/fashion.avif" alt="Image">
                    </div>
                    <div>
                    </div>
                    <div class="fbox-content">
                        <h3>Juste pour vous <span class="subtitle">Nos accessoires préférés </span></h3>
                        <p><a href="#" class="btn btn-secondary">Shoppe la tendance</a></p>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-lg-4">
                <div class="feature-box text-center media-box fbox-bg">
                    <div class="fbox-media">
                        <img src="/img/chemise.avif" alt="Image">
                    </div>
                    <div class="fbox-content">
                        <h3>Un style chic et moderne <span class="subtitle"> À adopter cette saison</span></h3>
                        <p><a href="#" class="btn btn-secondary">Shoppe l'élégance </a></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="fancy-title title-border title-center topmargin-sm">
            <h4>Nos marques</h4>
        </div>
        <div id="oc-clients-full" class="owl-carousel image-carousel carousel-widget" data-margin="30" data-nav="false" data-autoplay="5000" data-pagi="false" data-items-xs="2" data-items-sm="3" data-items-md="4" data-items-lg="5" data-items-xl="7">

            <div class="oc-item"><a href="#"><img src="/assets/images/logo/1.png" alt="test"></a></div>
            <div class="oc-item"><a href="#"><img src="/assets/images/logo/2.png" alt="Clients"></a></div>
            <div class="oc-item"><a href="#"><img src="/assets/images/logo/3.png" alt="Clients"></a></div>
            <div class="oc-item"><a href="#"><img src="/assets/images/logo/4.png" alt="Clients"></a></div>
            <div class="oc-item"><a href="#"><img src="/assets/images/logo/5.png" alt="Clients"></a></div>
            <div class="oc-item"><a href="#"><img src="/assets/images/logo/6.png" alt="Clients"></a></div>
            <div class="oc-item"><a href="#"><img src="/assets/images/logo/7.png" alt="Clients"></a></div>
            <div class="oc-item"><a href="#"><img src="/assets/images/logo/8.png" alt="Clients"></a></div>
            <div class="oc-item"><a href="#"><img src="/assets/images/logo/9.png" alt="Clients"></a></div>
            <div class="oc-item"><a href="#"><img src="/assets/images/logo/10.png" alt="Clients"></a></div>

        </div>

        <div>&emsp;</div>

        <div class="fancy-title title-border title-center topmargin-sm">
            <h4>Nos garanties</h4>
        </div>


        <div class="row col-mb-50">
            <div class="col-sm-6 col-lg-3">
                <div class="feature-box fbox-plain fbox-dark fbox-sm">
                    <div class="fbox-icon">
                        <i class="icon-thumbs-up2"></i>
                    </div>
                    <div class="fbox-content">
                        <h3>
                            <font color="#FF6900">Marques Originales</font>
                        </h3>
                        <p class="mt-0">Des marques 100% originales.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3">
                <div class="feature-box fbox-plain fbox-dark fbox-sm">
                    <div class="fbox-icon">
                        <i class="icon-credit-cards"></i>
                    </div>
                    <div class="fbox-content">
                        <h3>
                            <font color="#FF6900">Moyens de paiement</font>
                        </h3>
                        <p class="mt-0">Nous acceptons Visa, MasterCard et American Express..</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3">
                <div class="feature-box fbox-plain fbox-dark fbox-sm">
                    <div class="fbox-icon">
                        <i class="icon-truck2"></i>
                    </div>
                    <div class="fbox-content">
                        <h3>
                            <font color="#FF6900"> Livraison Gratuite</font>
                        </h3>
                        <p class="mt-0">Gratuit– pour toute commande de plus de 40,00 €.</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3">
                <div class="feature-box fbox-plain fbox-dark fbox-sm">
                    <div class="fbox-icon">
                        <i class="icon-undo"></i>
                    </div>
                    <div class="fbox-content">
                        <h3>
                            <font color="#FF6900"> Retour Gratuit</font>
                        </h3>
                        <p class="mt-0">Retour et échange sous 30 jours.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</div>


<div class="si-sticky si-sticky-right d-none d-lg-block" style="z-index: 399;">
    <a href="#" class="social-icon si-colored si-facebook" data-animate="bounceInRight">
        <i class="icon-facebook"></i>
        <i class="icon-facebook"></i>
    </a>
    <a href="#" class="social-icon si-colored si-twitter" data-animate="bounceInRight" data-delay="100">
        <i class="icon-twitter"></i>
        <i class="icon-twitter"></i>
    </a>
    <a href="#" class="social-icon si-colored si-pinterest" data-animate="bounceInRight" data-delay="200">
        <i class="icon-pinterest"></i>
        <i class="icon-pinterest"></i>
    </a>
    <a href="#" class="social-icon si-colored si-instagram" data-animate="bounceInRight" data-delay="300">
        <i class="icon-instagram"></i>
        <i class="icon-instagram"></i>
    </a>
    <a href="#" class="social-icon si-colored si-gplus" data-animate="bounceInRight" data-delay="600">
        <i class="icon-gplus"></i>
        <i class="icon-gplus"></i>
    </a>
    <a href="#" class="social-icon si-colored si-rss" data-animate="bounceInRight" data-delay="700">
        <i class="icon-rss"></i>
        <i class="icon-rss"></i>
    </a>
</div>
</div>