<!--getoneaccessoire -->
<div id="portfolio" class="portfolio row grid-container gutter-30" data-layout="fitRows">
    <?php
    foreach ($accessories as $accessory) {
        //d($accessory);

    ?>
        <article class="portfolio-item col-md-4 col-sm-6 col-12 pf-material<?= $accessory->id_material; ?>">
            <div class="grid-inner">
                <div class="portfolio-image">
                    <a href="#">
                        <img id="loading" src="/img/<?= $accessory->img; ?>" class="avatar avatar-sm me-3 border-radius-lg" style=" width:200 !important">
                    </a>

                    <div class="bg-overlay">
                        <div class="bg-overlay-content dark" data-hover-animate="fadeIn">
                            <a href="#" class="overlay-trigger-icon bg-light text-dark" data-hover-animate="fadeInDownSmall" data-hover-animate-out="fadeOutUpSmall" data-hover-speed="350" data-lightbox="image" title="Image"><i class="icon-line-plus"></i></a>
                            <a href="#" class="overlay-trigger-icon bg-light text-dark" data-hover-animate="fadeInDownSmall" data-hover-animate-out="fadeOutUpSmall" data-hover-speed="350"><i class="icon-line-ellipsis"></i></a>
                        </div>
                        <div class="bg-overlay-bg dark" data-hover-animate="fadeIn"></div>
                    </div>

                </div>
                <div class="portfolio-desc">
                    <h3>
                        <a href="<?= $this->url('detail_accessory', ['action' => 'index', 'id' => $accessory->id]) ?>"><?= $accessory->name; ?></a>

                    </h3>

                    <span>
                        <a href=" #">
                            <?= $accessory->name_brand; ?>
                        </a>
                    </span>
                </div>


            </div>
        </article>
    <?php
    }
    ?>